ayangweb/BongoCat

- src/composables/useModel.ts
- src/constants/index.ts
- src/pages/main.vue
- src/utils/live2d.ts
- 添加 live2d 单例模式
- 抽离业务逻辑和模型逻辑
- 支持模型mode切换+持久化
- 窗口切换大小时增加遮罩，减少模型重绘，提高性能
> refactor: abstract live2d class and refactor hook logic

- src/composables/useTray.ts
> fix: 任务栏图标菜单的窗口穿透和界面UI的窗口穿透相反

- src-tauri/tauri.conf.json
> feat: 窗口增加最小宽高

- src-tauri/tauri.conf.json
> feat: 将应用归类为「游戏」类别

- src/components/pro-list-item/index.vue
- src/pages/cat/index.vue
- src/pages/main/index.vue
- src/stores/cat.ts
> feat: 新增「猫咪设置 > 窗口设置 > 透明度」配置项

- src/pages/cat/index.vue
- src/pages/main/index.vue
- src/stores/cat.ts
> feat: 新增「猫咪设置 > 窗口设置 > 镜像模式」配置项

- src/composables/useDevice.ts
> fix: 修复了 `CapsLock` 按下后未正确释放的问题

- src/App.vue
> fix: 修复了 `v0.2.0` 版本中界面无法显示的问题

- Cargo.lock
- src-tauri/Cargo.toml
> fix: 修复 macOS 上鼠标按下后无法跟踪移动的问题

- Cargo.lock
- package.json
- pnpm-lock.yaml
- src-tauri/Cargo.toml
- src-tauri/capabilities/default.json
- src-tauri/src/lib.rs
- src/pages/preference/components/general/index.vue
- src/stores/general.ts
> feat: 增加开机自启功能

- src/composables/useSharedMenu.ts
- src/composables/useTray.ts
- src/pages/main/index.vue
- src/pages/preference/components/cat/index.vue
- src/stores/cat.ts
> feat: 支持通过右键菜单快捷操作猫猫

- src/pages/main/index.vue
> fix: 修复了重启后穿透效果失效的问题

- src/components/update-app/index.vue
> fix: 修复更新进度显示为 NaN 的问题

- src/composables/useModel.ts
- src/utils/dom.ts
- src/utils/monitor.ts
> fix: 修复了多显示器鼠标移动异常的问题

- src/composables/useWindowState.ts
> fix: 修复猫猫窗口靠左停靠后，重启时位置无法恢复的问题

- src/composables/useWindowState.ts
> fix: 修复因之前窗口在已移除的显示器上，导致重启后窗口不可见的问题

- src-tauri/src/core/setup/macos.rs
- src-tauri/src/plugins/window/build.rs
- src-tauri/src/plugins/window/permissions/default.toml
- src-tauri/src/plugins/window/src/commands/macos.rs
- src-tauri/src/plugins/window/src/commands/mod.rs
- src-tauri/src/plugins/window/src/commands/not_macos.rs
- src-tauri/src/plugins/window/src/lib.rs
- src/pages/main/index.vue
- src/pages/preference/components/cat/index.vue
- src/plugins/window.ts
- src/stores/cat.ts
> feat: 新增「猫咪设置 > 窗口设置 > 窗口置顶」配置项

- src/pages/preference/index.vue
> fix: 修复偏好设置目录右键选中问题

- .vscode/settings.json
> chore: 提示VSCode使用工作区的TS版本

- src/composables/useTray.ts
- src/pages/main/index.vue
> fix: 修复托盘菜单状态无法实时更新的问题

- src/pages/preference/components/model/index.vue
> feat: 支持点击模型卡片切换模型

- src/pages/preference/components/model/index.vue
> fix: 修复模型删除按钮缺失的问题

- src/pages/preference/components/model/components/upload/index.vue
- src/pages/preference/components/model/index.vue
> feat: 对模型管理上传组件添加响应式高度支持

- src/App.vue
- src/composables/useModel.ts
- src/stores/model.ts
> fix: 修复了部分场景下模型重叠的问题

- src-tauri/capabilities/default.json
- src-tauri/src/plugins/window/build.rs
- src-tauri/src/plugins/window/permissions/default.toml
- src-tauri/src/plugins/window/src/commands/common.rs
- src-tauri/src/plugins/window/src/commands/macos.rs
- src-tauri/src/plugins/window/src/lib.rs
- src/pages/main/index.vue
- src/pages/preference/components/about/index.vue
- src/pages/preference/components/cat/index.vue
- src/pages/preference/components/general/index.vue
- src/pages/preference/components/shortcut/index.vue
- src/plugins/window.ts
- src/stores/general.ts
> feat: 新增「通用设置 > 应用设置 > 显示任务栏图标」配置项

- src/composables/useDevice.ts
> fix: 修复 Windows 按键未正确记录的问题

- src-tauri/capabilities/default.json
- src/App.vue
- src/components/pro-list-item/index.vue
- src/pages/main/index.vue
- src/pages/preference/components/general/components/theme-mode/index.vue
- src/pages/preference/components/general/index.vue
- src/pages/preference/index.vue
- src/stores/general.ts
- src/stores/model.ts
> feat: 新增「通用设置 > 外观设置 > 主题模式」配置项

- src/App.vue
- src/pages/main/index.vue
- src/pages/preference/components/cat/index.vue
- src/pages/preference/components/general/components/theme-mode/index.vue
- src/stores/general.ts
> feat: 支持按住 `Shift` 并鼠标右键拖动调整窗口大小

- src/pages/main/index.vue
> fix: 修复了部分模型图片显示异常的问题

- src/App.vue
- src/pages/main/index.vue
- src/stores/app.ts
> fix: 修复版本号显示不正确的问题

- src/App.vue
- src/components/update-app/index.vue
- src/composables/useModel.ts
- src/composables/useSharedMenu.ts
- src/composables/useTray.ts
- src/pages/main/index.vue
- src/pages/preference/components/cat/index.vue
- src/pages/preference/components/general/components/theme-mode/index.vue
- src/pages/preference/components/general/index.vue
- src/pages/preference/components/shortcut/index.vue
- src/stores/cat.ts
- src/stores/general.ts
> feat: 新增「猫咪设置 > 窗口设置 > 窗口圆角」配置项
